// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmxlcGZuUpstz6zuIrIS2Om6Tsz_JPr14',
    appId: '1:891147691763:web:799687a69b9cdfc5ff7986',
    messagingSenderId: '891147691763',
    projectId: 'se334p21-ebook-reader',
    authDomain: 'se334p21-ebook-reader.firebaseapp.com',
    storageBucket: 'se334p21-ebook-reader.firebasestorage.app',
    measurementId: 'G-88W2H9S6VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC24sbWslwHng_7wuuYkuMY0PDpGEUCZto',
    appId: '1:891147691763:android:52b69183cd16f437ff7986',
    messagingSenderId: '891147691763',
    projectId: 'se334p21-ebook-reader',
    storageBucket: 'se334p21-ebook-reader.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjhFBZtcRhYjCSBdYkPM6yWWYi0_7hkEA',
    appId: '1:891147691763:ios:2fea0a9817dfbc6fff7986',
    messagingSenderId: '891147691763',
    projectId: 'se334p21-ebook-reader',
    storageBucket: 'se334p21-ebook-reader.firebasestorage.app',
    iosBundleId: 'com.example.ebookReader',
  );
}
